# Generated by Django 5.1.5 on 2025-05-02 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
